version: '1'
services: 
  pg_master:
    image: postgres:latest
    container_name: pg_master
    user: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: |
      postgres 
      -c wal_level=logical
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c listen_addresses="*"
    volumes:
      - ./scripts/create_master.sql:/docker-entrypoint-initdb.d/create_master.sql
      - ./scripts/procedure.sql:/docker-entrypoint-initdb.d/procedure.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
  pg_replica:
    image: postgres:latest
    container_name: pg_replica
    user: postgres
    ports:
      - 5433:5432
    depends_on:
      pg_master:
        condition: service_healthy
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: |
      postgres 
      -c listen_addresses="*"
    volumes:
      - ./scripts/create_replica.sql:/docker-entrypoint-initdb.d/create_replica.sql
